### ISSUE TITLE
Congratulations :-)

### ISSUE THREAD

**Issue by hmeine** [realpython/realpython-blog#16]
I am sorry for abusing GitHub as a comments system – I could not get Disqus to work (it is blocked by default for me, and after trying to deactivate all blockers and reloading, the comments section disappeared entirely).

I just wanted to thank you and congratulate for the nice "Emacs as a Python IDE" post – actually, I am a long-term (~20 years?) Emacs user, and I have seen a lot of material already.  That said – your post is really great in the sense that it does not dump a large config on the reader, but really explains the most important things and shows some nice features.  I will point colleagues interested in Emacs to your blog from now on. :-)

**Comment by mjhea0** [comment]
Thanks! :)
